kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-task
  namespace: try-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: manual
